from scrapy.exceptions import DropItem

# -*- coding: utf-8 -*-

# Define your item pipelines here
#
# Don't forget to add your pipeline to the ITEM_PIPELINES setting
# See: http://doc.scrapy.org/en/latest/topics/item-pipeline.html


class EmailPipeline(object):
    def open_spider(self, spider):
        self.emails = set() # Instantiates the set when the spider first starts

    def process_item(self, item, spider):
        """
        This function is called for every EmailItem that is generated by
        EmailSpider. It checks whether the email has been seen before using
        the set, adds new emails to the set, and raises DropItems when the
        email has already been seen (or doesn't exist at all). DropItems
        indicate that the item is to be skipped.
        """
        email = item['email']
        if not email or email in self.emails:
            raise DropItem("%s dropped from pipeline" % item)
        else:
            self.emails.add(email)
            print email
        return item